# Generated by Django 2.2.19 on 2021-04-13 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0002_auto_20210412_2148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleado',
            name='permiso',
        ),
    ]
