# Generated by Django 2.2.19 on 2021-04-13 02:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0003_remove_empleado_permiso'),
        ('permisos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='permiso',
            name='empleado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='permisos', to='empleados.Empleado'),
        ),
    ]
